### ISSUE TITLE
YouTube loading happens on load not when slide is active / ready

### ISSUE THREAD

**Issue by MiczFlor** [Inkmap/Docmint#9]
A slideshow with youtube background videos, using the new plugin [background-youtube-video.js](https://github.com/Inkmap/WebDocCanvas/blob/master/vendor/revealjs/plugin/background-youtube-video/background-youtube-video.js) is contacting YouTube when the page is loaded.
It should not require to contact YouTube until the slide containing the iframe background with YouTube is ready. Is it possible to use the [slide state event of reveal.js](https://github.com/hakimel/reveal.js/blob/master/README.md#slide-states) on a slide with a unique state for each slide with a video?

**Comment by justmarkup** [comment]
The youtube API loaded via JavaScript has to be ready before the iframe background with YouTube is ready in order to handle all events correctly and to be able to open a page containing a video directly (eg. #/3). The video itself is currently only requested if a slide containing the video is visible.
